on:
  schedule:
  - cron: "40 11 * * *"
    
name: update-website

jobs:
  update-website:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '3.6'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", 'bookdown','DBI','RMariaDB','data.table','knitr','rmarkdown','DT','webshot','PhantomJS'))
        shell: Rscript {0}
      - name: Refresh book
        run: |
          db_user <- "${{secrets.USER}}"
          
          db_ip <- "${{secrets.IP}}"
          
          db_pswd <- "${{secrets.PSWD}}"
          
          bookdown::render_book('index.Rmd', 'bookdown::gitbook', clean_envir = FALSE)
        shell: Rscript {0}
      - name: Install npm
        uses: actions/setup-node@v1
      - name: Commit files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git commit -m "Update book" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_PAT }}
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _book
